### ISSUE TITLE
polymer-selector throws Uncaught DataCloneError: An object could not be cloned

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#61] opened 2013-11-04 14:34 UTC
polymer-selector throws 'Uncaught DataCloneError: An object could not be cloned'.

**Comment by ErikGrimes** [comment] 2013-11-04 14:34
Waiting on feedback on [this thread](https://groups.google.com/a/dartlang.org/forum/#!topic/web-ui/UKhjAwAKEkw).

**Comment by zoechi** [comment] 2014-01-08 12:46
Should be fixed [Uncaught Error: DataCloneError](https://code.google.com/p/dart/issues/detail?id=14779)

**Comment by zoechi** [comment] 2014-01-08 13:05
Couldn't reproduce

**Closed as completed by zoechi** 2014-01-08 13:05 UTC
Labels: status:accepted, status:blockedDart, status:fixed
